version: "3.3" 

services:

  web-metabase:
    build: .
    volumes:
      - .:/code
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    depends_on:
      - db-metabase

  db-metabase:
    image: postgres:14-alpine
    volumes:
      - /var/lib/docker/volumes/postgres_mining/_data:/var/lib/postgresql/data/
    ports:
      - 5439:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - /var/lib/docker/volumes/metabase_mining/_data:/metabase-data
    depends_on:
      - db-metabase
