# Generated by Django 4.2.3 on 2023-07-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('time_internal', models.DateTimeField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('dest_wallet_id', models.BigIntegerField()),
                ('transaction_type', models.IntegerField()),
                ('transaction_type_chain', models.CharField(max_length=128)),
                ('wallet_nickname', models.CharField(blank=True, max_length=16, null=True)),
                ('transaction_cost', models.BigIntegerField()),
                ('transaction_value', models.BigIntegerField()),
                ('bank_id', models.IntegerField()),
                ('transaction_gateway_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE data_dataset DROP CONSTRAINT data_dataset_pkey;"
        ),
    ]
